# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  tools:
    python: "3.9"
  os: "ubuntu-20.04"
python:
  install:
    # We are using "pip" to install
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs
